# 콘솔에 한글 깨짐 방지
server:
  servlet:
    encoding:
      force-response: true

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  config:
    import:
      - classpath:application-mail.yml
      - classpath:application-redis.yml

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
