spring:
  config:
    import:
      - classpath:application-mail.yml
      - classpath:application-redis.yml
      - classpath:application-notion.yml
      - classpath:application-oauth2.yml
      - classpath:application-s3.yml

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  url: "localhost:8080"